### ISSUE TITLE
Different Scala version?

### ISSUE THREAD

**Issue by cheeven** [frol/docker-alpine-scala#1]
Hello,

I have found your frolvlad/alpine-oraclejdk8 docker image extremely useful and have been happily using that for a while. 

I found and am quite excited to find your Scala image because I am a Scala developer myself. As you probably know, Scala classes are binary-incompatible across major versions (2.10.x, 2.11.x, 2.12.x) and if I want to use this image, I am limited to the experimental 2.12.x Scala - however, most of my application are still on 2.11.x.

Is it possible to set up multiple branches for this image for different major versions of Scala, in the same way like openjdk (https://github.com/docker-library/openjdk) ?

I think it will be very useful to have the following branches:
- 2.10 (2.10.6)
- 2.11 (2.11.8)
- 2.12 (2.12.0-M4)
- latest

Thanks a lot!

Cheeven

**Comment by frol** [comment]
Thank you for coming back with the request making things better!

I will make the branches now since it doesn't seem to be too hard to maintain anyway.

**Comment by frol** [comment]
```
$ docker run -it --rm frolvlad/alpine-scala:latest scalac -version
Scala compiler version 2.12.0-M4 -- Copyright 2002-2016, LAMP/EPFL

$ docker run -it --rm frolvlad/alpine-scala:2.12 scalac -version
Scala compiler version 2.12.0-M4 -- Copyright 2002-2016, LAMP/EPFL

$ docker run -it --rm frolvlad/alpine-scala:2.11 scalac -version
Scala compiler version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL

$ docker run -it --rm frolvlad/alpine-scala:2.10 scalac -version
Scala compiler version 2.10.6 -- Copyright 2002-2013, LAMP/EPF
```
